#!/usr/bin/env bash
# Installs and setup haproxy
apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy
echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 17272-web-01 34.207.189.159:80 check
   server 17272-web-02 18.209.223.224:80 check" >> /etc/haproxy/haproxy.cfg

service haproxy start
