#!/usr/bin/env bash
# printing best school but hi in the 9th iterations

i=0
while [ $i -lt 10 ]
do
	if [ $i -eq 3 ] ; then
	echo "bad luck"
	elif [ $i -eq 7 ] ; then
	echo "good luck"
	else
	echo "Best School"
	fi
	((i++))
done
