#!/usr/bin/env bash
#localhost resolves to 127.0.0.2
#facebook.com resolves to 8.8.8.8

cp /etc/hosts ~/hosts.tmp
sed -i "s/^127\.0\.0\.1/127.0.0.2/" ~/hosts.tmp
echo "8.8.8.8		facebook.com" >> ~/hosts.tmp
cp -f ~/hosts.tmp /etc/hosts
